version: '{build}'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true
skip_branch_with_pr: true

image:
- Visual Studio 2022
- Ubuntu2204

configuration:
- Debug
- Mixed
- Release
- Release Master Gold

platform:
- x64
- x86

branches:
  except:
    - dependabot/*

matrix:
  exclude:
    - image: Ubuntu2204
      platform: x86
    - image: Ubuntu2204
      configuration: Mixed
    - image: Ubuntu2204
      configuration: Release Master Gold

cache:
- src/packages -> **/packages.config

for:
-
  matrix:
    only:
      - image: Visual Studio 2022

  before_build:
    - git submodule update --init --recursive
    - nuget restore src\engine.sln

  build:
    project: src/engine.sln
    parallel: true
    verbosity: minimal

  after_build:
    - cmd: misc/windows/xr_pack_build.cmd "%CONFIGURATION%" "%PLATFORM%"

  artifacts:
    - path: res/OpenXRay.*.7z
      name: OpenXRay.*.7z
    - path: res/Symbols.*.7z
      name: Symbols.*.7z
    - path: res/Utils.*.7z
      name: Utils.*.7z
-
  matrix:
    only:
      - image: Ubuntu2204

  before_build:
    - sudo apt-get update
    - sudo apt-get install -y libsdl2-dev libglew-dev liblzo2-dev libjpeg-dev libopenal-dev libogg-dev libtheora-dev libvorbis-dev
    - git submodule update --init --recursive

  build_script:
    - ${CXX} --version
    - cmake --version
    - export core_count=$(nproc || echo 4) && echo core_count = $core_count
    - CFLAGS="-w" CXXFLAGS="-w" cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - cmake --build build --config $BUILD_CONFIGURATION --parallel $core_count
    - cpack -B artifacts -C $BUILD_CONFIGURATION -DCPACK_THREADS=$core_count
    - file openxray_1.6.02_*.deb

  artifacts:
    - path: bin/openxray_1.6.02_*.deb
      name: openxray_1.6.02_*.deb

test: off

deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: OpenXRay (build $(appveyor_build_version))
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: kGVniXDR926BfVcA97y25BzALbijvgboBsozZzY9yc8RPz15Q4YG474h7vl14/J1
  artifact:
    OpenXRay.*.7z, Symbols.*.7z, Utils.*.7z
  draft: true
  force_update: true
